/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  AccessTokens: () => import('#controllers/access_tokens_controller'),
  AiCommands: () => import('#controllers/ai_commands_controller'),
  Auth: () => import('#controllers/auth_controller'),
  NewAccount: () => import('#controllers/new_account_controller'),
  Profile: () => import('#controllers/profile_controller'),
  Projects: () => import('#controllers/projects_controller'),
  Tasks: () => import('#controllers/tasks_controller'),
}
